export default {
  EVENT_TYPES: {
    CHANGE_EVENT: 'CHANGE_EVENT',
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGIN'
  },

  AUTH_ACTION_TYPES: {
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    LOG_IN_SUCCESS: 'AUTH_LOG_IN_SUCCESS',
    LOG_OUT_SUCCESS: 'AUTH_LOG_OUT_SUCCESS'
  }
};