export const AUTH_ACTION_TYPES = {
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  LOG_IN_SUCCESS: 'AUTH_LOG_IN_SUCCESS',
  LOG_OUT_SUCCESS: 'AUTH_LOG_OUT_SUCCESS'
};